map_background=F1F3F4
map_missing=E8EAED
labels=5F6368
labels_strong=3C4043
labels_bgcolor=FFFFFF
oneWay=5F636866
points=AECBFA
selection=4285F4
freeways=A8B4C4
primary=B8C1CC
secondary=D1D6DC
highways=C4CDD7
street=FFFFFF
private=F8F9FA
trails4x4=DDD5BF
alleys=FFFFFF
ramps=B8C1CC
parking=FFFFFF
parking_lots=E4E7EA
parking_lots_pins=D2E3FC
railroads=C5C9CD
ferry_stroke=7AAFC2
pedestrian=E2E5E8
trails=DEDACE
walkway=E2E5E8
cities=E8EAED
stations=DADCE0
parks=C5E8C5
sea=A3D5E5
lakes=A3D5E5
rivers=A3D5E5
label_station=70757A
label_cities=3C4043
label_vegetation=287A48
label_water=397D99
ad_labels_color=5F6368
ad_labels_outline_color=FFFFFF
navigation=4285F4
stop_point=1A73E8
snail=AECBFA
snail_via=D2E3FC
detour=BDC9DB
detour_stroke=8596B0
alt_color_1=8AB4F8
alt_color_2=7BAAF7
alt_color_3=AECBFA
alt_color_current=4285F4
route_preview_unselected_fill=BDC9DB
route_preview_unselected_stroke=8596B0
