map_background=202124
map_missing=292A2D
labels=BDC1C6
labels_strong=E8EAED
labels_bgcolor=202124E6
oneWay=E8EAED66
points=8AB4F8
selection=8AB4F8
freeways=747A83
primary=646A73
secondary=50555D
highways=5F6368
street=45494F
private=3C4043
trails4x4=4C4941
alleys=3C4043
ramps=646A73
parking=45494F
parking_lots=303134
parking_lots_pins=3C4658
railroads=555A60
ferry_stroke=456575
pedestrian=3C4043
trails=42453E
walkway=3C4043
cities=25272A
stations=303134
parks=263E32
sea=172C3C
lakes=172C3C
rivers=172C3C
label_station=9AA0A6
label_cities=E8EAED
label_vegetation=81B58E
label_water=7FA9BF
ad_labels_color=BDC1C6
ad_labels_outline_color=202124E6
navigation=8AB4F8
stop_point=AECBFA
snail=394F73
snail_via=394F73
detour=5E6B80
detour_stroke=3F4B60
alt_color_1=6686B8
alt_color_2=7898C9
alt_color_3=9BB9E8
alt_color_current=8AB4F8
route_preview_unselected_fill=5E6B80
route_preview_unselected_stroke=3F4B60
